### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'

### ISSUE THREAD

**Issue by DesireHope** [fenchri/edge-oriented-graph#5] opened 2019-11-15 03:46 UTC
sh process_cdr.sh 
11923it [00:00, 189285.60it/s]
Processing Doc_ID 227508:   0%|                                                             | 0/500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "process.py", line 123, in <module>
    main()
  File "process.py", line 62, in main
    split_sents = sentence_split_genia(orig_sentences)
  File "/home/deep/dp/edge-oriented-graph/data_processing/tools.py", line 248, in sentence_split_genia
    with open('temp_file.split.txt', 'r') as ifile:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_file.split.txt'

**Comment by fenchri** [comment] 2019-11-16 13:25
I would suggest to try to re-install again the genia-tagger and run the pre-processing process again.

**Comment by Christiannov** [comment] 2019-11-19 12:23
@DesireHope Hello, I have encountered the same problem. Have you solved this problem?

**Comment by fenchri** [comment] 2019-11-19 12:46
Did you stop the processing at some point by mistake?
Try to re-run the processing script again maybe?

**Comment by DesireHope** [comment] 2019-11-19 12:50
> @DesireHope Hello, I have encountered the same problem. Have you solved this problem?

No, i try to reinstall genia-tagger but still fail

**Comment by fenchri** [comment] 2019-11-19 12:54
Hello both!
This error means that the genia-sentence-splitter did not run. 
I cloned the repository from the start and applied the steps described one-by-one (in the readme), and the problem did not occur.
Please make sure you first cd into the repository and then follow the steps.

Could you please try again?

**Comment by Christiannov** [comment] 2019-11-19 13:41
Hello @DesireHope, @fenchri !
Thank you for response! 
I've just solved the problem. For my situation, this is because ruby is not installed in the environment. So I just installed ruby and the problem is solved.
Hope this helps @DesireHope.

**Comment by DesireHope** [comment] 2019-11-19 13:48
> Hello @DesireHope, @fenchri !
> Thank you for response!
> I've just solved the problem. For my situation, this is because ruby is not installed in the environment. So I just installed ruby and the problem is solved.
> Hope this helps @DesireHope.

Thank you！I have solved the problem.

**Comment by DesireHope** [comment] 2019-11-19 13:49
> Hello both!
> This error means that the genia-sentence-splitter did not run.
> I cloned the repository from the start and applied the steps described one-by-one (in the readme), and the problem did not occur.
> Please make sure you first cd into the repository and then follow the steps.
> 
> Could you please try again?

Thank you! I have solved the problem.

**Comment by fenchri** [comment] 2019-11-19 14:00
Good to hear! I am closing this then :)

**Closed as completed by fenchri** 2019-11-19 14:00 UTC
